### ISSUE TITLE
wiki公式计算

### ISSUE THREAD

**Issue by CCCCoder** [OCNYang/ContuorView#2]
A和B的坐标到底是怎么得出来的？

**Comment by OCNYang** [comment]
![简单来说](http://obbu6r1mi.bkt.clouddn.com/github/contourview/bzejs.png)   
简单来说就是上面这种求法：想求两个点之间的控制点，你需要知道这两个点的前后点的坐标，也就是说至少需要4个点的坐标才能求两个点之间曲线的控制点。（这种公式化的符号真的难打，markdown也不支持，只能用word再截图了）

**Comment by CCCCoder** [comment]
明白了。谢谢~

**Comment by CCCCoder** [comment]
@OCNYang 明白了。蟹蟹~
